var courseList = [
  { 
    id: 1, 
    isShow:false,
    color:false,
    bgSrc: "images/lockbg2.png",
    titleImg: "images/paint.png",
    titleText: "幼猫课", 
    courseNum: "Lesson 1 ", 
    courseTitle: "如何照看离乳期幼猫" ,
    videoSrc: "##",
    videoBg: "images/videobg1.jpg"
  },
  { 
    id: 2, 
    isShow:false,
    color:false,
    bgSrc: "images/lockbg2.png",
    titleImg: "images/paint.png",
    titleText: "幼猫课", 
    courseNum: "Lesson 2 ", 
    courseTitle: "如何照看离乳期幼猫" ,
    videoSrc: "##",
    videoBg: "images/videobg1.jpg"
  },
  { 
    id: 3,
    isShow:true,
    color:false, 
    bgSrc: "images/lockbg2.png",
    titleImg: "images/paint.png",
    titleText: "幼猫课", 
    courseNum: "Lesson 3", 
    courseTitle: "如何照看离乳期幼猫" ,
    videoSrc: "##",
    videoBg: "images/videobg1.jpg"
  },
  { 
    id: 4, 
    isShow:true,
    color:false,
    bgSrc: "images/lockbg2.png",
    titleImg: "images/paint.png",
    titleText: "幼猫课", 
    courseNum: "Lesson 4 ", 
    courseTitle: "如何照看离乳期幼猫" ,
    videoSrc: "##",
    videoBg: "images/videobg1.jpg"
  },
  { 
    id: 5, 
    isShow:true,
    color:false,
    bgSrc: "images/lockbg2.png",
    titleImg: "images/paint.png",
    titleText: "幼猫课", 
    courseNum: "Lesson 5 ", 
    courseTitle: "如何照看离乳期幼猫 " ,
    videoSrc: "##",
    videoBg: "images/videobg1.jpg"
  },
  { 
    id: 6, 
    isShow:true,
    color:true,
    bgSrc: "images/lockbg1.png",
    titleImg: "images/stem.png",
    titleText: "成猫课", 
    courseNum: "Lesson 6 ", 
    courseTitle: "如何照看成猫" ,
    videoSrc: "##",
    videoBg: "images/videobg2.jpg"
  },
  { 
    id: 7, 
    isShow:true,
    color:false,
    bgSrc: "images/lockbg2.png",
    titleImg: "images/paint.png",
    titleText: "幼猫课", 
    courseNum: "Lesson 7 ", 
    courseTitle: "如何照看离乳期幼猫" ,
    videoSrc: "##",
    videoBg: "images/videobg1.jpg"
  },
  { 
    id: 8, 
    isShow:true,
    color:false,
    bgSrc: "images/lockbg2.png",
    titleImg: "images/paint.png",
    titleText: "幼猫课", 
    courseNum: "Lesson 8 ", 
    courseTitle: " 如何照看离乳期幼猫" ,
    videoSrc: "##",
    videoBg: "images/videobg1.jpg"
  },
  { 
    id: 9, 
    isShow:true,
    color:false,
    bgSrc: "images/lockbg2.png",
    titleImg: "images/paint.png",
    titleText: "幼猫课", 
    courseNum: "Lesson 9 ", 
    courseTitle: "如何照看离乳期幼猫" ,
    videoSrc: "##",
    videoBg: "images/videobg1.jpg"
  },
  { 
    id: 10, 
    isShow:true,
    color:false,
    bgSrc: "images/lockbg2.png",
    titleImg: "images/paint.png",
    titleText: "幼猫课", 
    courseNum: "Lesson 10 ", 
    courseTitle: "如何照看离乳期幼猫" ,
    videoSrc: "##",
    videoBg: "images/videobg1.jpg"
  },
  { 
    id: 11, 
    isShow:true,
    color:false,
    bgSrc: "images/lockbg2.png",
    titleImg: "images/paint.png",
    titleText: "幼猫课", 
    courseNum: "Lesson 11 ", 
    courseTitle: "如何照看离乳期幼猫" ,
    videoSrc: "##",
    videoBg: "images/videobg1.jpg"
  },
  { 
    id: 12, 
    isShow:true,
    color:true,
    bgSrc: "images/lockbg1.png",
    titleImg: "images/stem.png",
    titleText: "成猫课", 
    courseNum: "Lesson 12 ", 
    courseTitle: "如何照看成猫" ,
    videoSrc: "##",
    videoBg: "images/videobg2.jpg"
  },
 
]